#!/bin/sh

# Log everything to /var/log/messages
exec 1> >(logger -s -p INFO -t console 2>&1)
exec 2> >(logger -s -p WARNING -t console)

# Source aawgd configuration environment variables
source /etc/aawgd.conf.sh
export AAWG_CONF_SOURCED=1

# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
        *.sh)
            # Source shell script for speed.
            (
                trap - INT QUIT TSTP
                set start
                . $i
            )
            ;;
        *)
            # No sh extension, so fork subprocess.
            $i start
            ;;
    esac
done
