#!/bin/sh
#
# Load kernel modules
#

case "$1" in
	start)
		echo "Loading kernel modules..."
		modprobe -a brcmfmac hci_uart # Wireless drivers
		modprobe -a dwc2 libcomposite # USB gadget drivers
		;;
	*)
		echo "Usage: $0 {start}"
		exit 1
esac

exit $?
