#!/bin/sh
#
# Setup persistent storage
#

case "$1" in
	start)
		echo "Setup persistent storage..."
		mkdir -p /persist/seedrng
		mkdir -p /persist/bluetooth
		;;
	*)
		echo "Usage: $0 {start}"
		exit 1
esac

exit $?
