#!/bin/sh
#
# Register bluetooth agent for non-interactive connection
#

DAEMON="bt-agent"
PIDFILE="/var/run/$DAEMON.pid"


RETVAL=0

case "$1" in
	start)
		printf "Starting $DAEMON: "
		start-stop-daemon -S -b -q -m -p "$PIDFILE" -x "/usr/bin/$DAEMON" -- --capability=NoInputNoOutput
		RETVAL=$?
		[ $RETVAL = 0 ] && echo "OK" || echo "FAIL"
		;;
	stop)
		printf "Stopping $DAEMON: "
		start-stop-daemon -K -q -p "$PIDFILE"
		RETVAL=$?
		[ $RETVAL = 0 ] && echo "OK" || echo "FAIL"
		;;
	*)
		echo "Usage: $0 {start|stop}"
		;;
esac

exit $RETVAL
