#!/bin/sh
#
# Mange Android Accessory events and lifecycle
#

DAEMON="bt-agent"
PIDFILE="/var/run/$DAEMON.pid"


RETVAL=0

case "$1" in
	start)
		start-stop-daemon -S -b -q -m -p "$PIDFILE" -x "/usr/bin/$DAEMON" -- --capability=NoInputNoOutput
		RETVAL=$?
		;;
	stop)
		start-stop-daemon -K -q -p "$PIDFILE"
		RETVAL=$?
		;;
	*)
		echo "Usage: $0 {start|stop}"
		;;
esac

exit $RETVAL
