#!/bin/sh
#
# Start aawgd daemon
#

DAEMON="aawgd"
PIDFILE="/var/run/$DAEMON.pid"


RETVAL=0

case "$1" in
	start)
		if [ -z "$AAWG_CONF_SOURCED" ]; then
			echo "Source /etc/aawgd.conf.sh"
			source /etc/aawgd.conf.sh
		fi

		printf "Starting $DAEMON: "
		start-stop-daemon -S -b -q -m -p "$PIDFILE" -x "/usr/bin/$DAEMON"
		RETVAL=$?
		[ $RETVAL = 0 ] && echo "OK" || echo "FAIL"
		;;
	stop)
		printf "Stopping $DAEMON: "
		start-stop-daemon -K -q -p "$PIDFILE"
		RETVAL=$?
		[ $RETVAL = 0 ] && echo "OK" || echo "FAIL"
		;;
	restart)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop}"
		;;
esac

exit $RETVAL
